### ISSUE TITLE
Mispronunciation of "one lives"

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#1]
Raveena and Amy both say "lives" in "one lives" as for "two lives".

**Comment by firepick1** [comment]
All AWS Polly English voices have this bug. It is a bug in Amazon Polly itself. Although we could work around it, we are deferring any work in the hopes that AWS will fix it itself due to global need.

**Comment by sabbamitta** [comment]
Voice currently finds "one lives" in eight suttas: https://voice.suttacentral.net/scv/index.html?r=0.805405100573058#/sutta?search=one%20lives, a concrete example being an5.141:1.3 (Amy).

**Comment by sabbamitta** [comment]
Checked and sent to icebox in v2.3.
