### ISSUE TITLE
Voice admins can create a VSM file and archive it to Wasabi

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#106]
#### Description
Propose using kn_pli_mahasangiti_aditi.tar.gz for the VSM file. KN is smaller than the other Nikayas.  Generating a VSM file will use a lot of AWS Polly calls, but I think that it will be within the AWS Polly Free Tier limitations of Aminah's account. If we do go over, I will reimburse Aminah for any charges. 

#### Acceptance criteria 
Full VSM file uploaded to MichaelH's S3 Admin account in `sc-voice-wasabi` bucket

**Comment by sabbamitta** [comment]
See discussion of testing [here](https://discourse.suttacentral.net/t/sc-voice-development-cycle-v1-5/12832/223?u=sabbamitta) and following posts.
