### ISSUE TITLE
merge humanUI branch into master

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#110]

**Comment by Aminah-SC** [comment]
@firepick1, particularly with consideration to (just updated #109) I think it might be best to keep the development of settings in its own branch; what do you think?

**Comment by firepick1** [comment]
Incorporated voice icons, settings groups, bell sound reduction into v1.5.22. Could not merge directly.

**Comment by sabbamitta** [comment]
Settings design is approved by everybody. Closing.
