### ISSUE TITLE
dot dot SarathW1

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#111]
@sabbamitta SN14.18:5.5 it reads “dot , dot”
Not a big issue though.
@karl_lew
SN14.20 it happens a lot and it is a problem. This is due to four … instead three dots.
Now You find it in many suttas. and will not report again.

**Comment by sabbamitta** [comment]
Which voice is it—Amy? (Then we have an Epic for that.)

**Comment by sabbamitta** [comment]
[SN22. 15-20 isolated dot problem](https://discourse.suttacentral.net/t/lets-read-bhante-sujatos-sutta-translations/9547/66?u=sabbamitta)

**Comment by firepick1** [comment]
Converted manuscript "..." to Unicode ellipsis character. Fixed in v1.5.23

**Comment by sabbamitta** [comment]
@karl_lew
The dot problem exists at least once in each Suttas from say SN22.140-159
It is not really disturbing. But good if removed. (see https://discourse.suttacentral.net/t/lets-read-bhante-sujatos-sutta-translations/9547/67?u=sabbamitta)

**Comment by sabbamitta** [comment]
Testing: Works fine for all the ellipses. Closing.
