### ISSUE TITLE
Speak ellipses with a silence of one second

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#114]
Bhante Sujato's translations often separate single words with ellipses, making it hard to hear the repetition implied in the ellipses.  In Pali, the ellipsis is spoken and heard as "pe". In English the ellipsis is silent or it is spoken using with a phrase such as "and so on" for emphasis.

> They meditate spreading a heart full of compassion … rejoicing 

Ideally, the translations would make use of  an introductory repetitive phrase such as:

> They meditate spreading a heart full of compassion …  
> They meditate spreading a heart full of rejoicing …  

However, it would be less disruptive to translation to lengthen the ellipsis pause to be heard and noticed.

**Comment by firepick1** [comment]
Fixed in v1.5.15. The ellipsis pause is configurabe by voice. The default is 1 second.  For Aditi, it is shorter at 0.3 seconds because of the accompanying "pe". This change will affect all VSMs and requires rebuilding them. It was for this reason I thought it best to complete the fix in v1.5 rather than later.

**Comment by sabbamitta** [comment]
Thanks so much for doing this! :pray: Will test ans rebuild VSM.

**Comment by sabbamitta** [comment]
Testing:
* I first happened on AN 10.62 where there are many instances of abbreviation in the English, and I'd say I'm pretty convinced of that.
* For the only two instances of abbreviation in the Pali I can't find a difference to what is on production, except that this "knocking" sound before the pronunciation of "pe" is in one case present on staging, but not on production. (I have noticed this "knocking" already before, but now as we are working on the ellipses it moves more into the focus.)
* A question: is the pause inserted *before* or *after* the "pe" in Pali? In MN 2 there are several instances of abbreviations at the end of a segment, and there I can't hear any pause, so my conclusion is the pause may be inserted after. In fact, I have not yet come across an instance of abbreviation in Pali that is *not* at the end of a segment; which may explain why there is no difference in pause between production and staging.

**Comment by sabbamitta** [comment]
I have now tried to listen to segments with "pe" in Pali only mode, but still there, at the segment break, there is a natural pause that is not different from the pause in the segments without a "pe" at the end. Still, I haven't seen any instance of a "pe" in the middle of a segment.

**Comment by sabbamitta** [comment]
Results approved by tester and respective VSM rebuilt. :heavy_check_mark:
