### ISSUE TITLE
Sutta player stops at sn12.1:1.2.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#115]
#### Bug Description
Found a bug on staging:

![Bildschirmfoto%20vom%202019-06-23%2019-35-09|530x525](upload://bYtDt5Ysztutg2fscZdyv5tsWQK.png) 

Playing this sutta, it gets stuck at this place. Also after trying multiple times, after stopping the sutta player, refreshing the page and starting again; after moving the blue dot to the next segment (which works fIne) and then moving it back again; couldn't think of more things to try out.

On production the same segment works fine.

#### Expected behaviour
The sutta player should play segment after segment.

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by sabbamitta** [comment]
Tried to update release on staging for testing, but it says "current release (v1.5.22) is latest). So I can't test.

**Comment by firepick1** [comment]
This only happens with sujato_pli voice. Aditi works fine. Investigating...

**Comment by sabbamitta** [comment]
The same happens in other Suttas too when Sujato is set as the speaker for Pali. Also when there is no Sujato recording and it falls back to Aditi (for example in SN

**Comment by firepick1** [comment]
Fixed in v1.5.26

**Comment by firepick1** [comment]
Fixed in v.1.5.27.  The recent failure had a different root cause. Voice mistook the error response for digitalocean as a sound file. In attempting to play the error message as a sound file, all intervening software got quite confused and simply gave up.

**Comment by sabbamitta** [comment]
And it works now!!!
