### ISSUE TITLE
Reduce VSM size

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#120]
Production disk space is limited. Reducing VSM size will delay the need to increase disk space.

**Comment by firepick1** [comment]
Suprisingly, it is not easy to reduce VSM size. In fact, VSMs built from atomic sound files are about only about 99% the size of VSMs built from composite sound files. In addition, atomic VSMs create slower caches. Because of this, we may need to increase Voice disk size to 30GB

**Comment by sabbamitta** [comment]
OK, then this is so.
