### ISSUE TITLE
Reduce log size

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#121]
Logs get big after many days and are hard to view during investigations. We should create a new log every day.

Possible solutions:
* reboot the sever daily as an Admin task
* reboot the server regularly automatically at a designated time
* use automatic daily log rotation

**Comment by firepick1** [comment]
Logs are now created using rotatelogs, which creates daily log files.

**Comment by sabbamitta** [comment]
From [issue 121](https://github.com/sc-voice/sc-voice/issues/121):
>To test, login as Admin on staging server and view a log.

:eyes:

![Bildschirmfoto%20vom%202019-07-04%2017-26-26|690x262](upload://1ouWdbyp2oPG0jqVmRXgbR2uKRC.png) 

Viewing a log, I see a veeery long list that doesn't fit in one screenshot... !

Approved and closed.
