### ISSUE TITLE
Replace staging server with new 30GB staging server on Aminah's AWS account.

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#126]
* create new EC2 instance per instructions in https://github.com/sc-voice/sc-voice/wiki/AWS-Installation
* terminate (destroy) existing staging server. At 16GB it is of no use.

We need staging server for testing and building VSMs.

**Comment by Aminah-SC** [comment]
https://35.176.116.11/scv/index.html#/sutta
