### ISSUE TITLE
Refresh sc-voice/scv-suttas

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#127]
SuttaCentral has newer content.

**Comment by firepick1** [comment]
Voice v1.6.3 is available with updated content.  Search for "meanwhile" with 50 search results. Production returns 11 suttas. Staging should return 12, including AN3.100. The content changes were rather massive yet mostly annotational (i.e., endless blurb changes) or cosmetic (i.e., changes in whitespace). It took me a while to find actual changes to content. AN3.100 was one of those whose content changed.

**Comment by sabbamitta** [comment]
Updates can be found now on Voice. Closing.
