### ISSUE TITLE
Search for "sona" returns less results than "Soṇa"

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#128]
Improper search results misrepresent what the Buddha said.

**Comment by firepick1** [comment]
Fixed in v1.6.11.  "sona" was mis-identified as an English word.

**Comment by sabbamitta** [comment]
"Soṇa" now returns 15 results, "sona" 39.

**Comment by firepick1** [comment]
"Soṇa" returns 6 results
"Soṇa" returns 13 results
"Soṇā" returns 5 results
"Sona" returns 21
"Sabbamitta" now returns...2 results. Yes. I had to fix THAT bug to fix THIS bug. :D
v.1.6.16

**Comment by sabbamitta** [comment]
> I had to fix THAT bug to fix THIS bug. :D

How did you guess this? :-)

Testing:
* "sona" returns 21 results
* "Soṇa" returns 8 results
* "Soṇā" returns 5 results
* "Soṇa.*" returns 16 results
* "Sona" returns 21 results

Sorry, it has to come back to "in progress"! :joy:

**Comment by firepick1** [comment]
Ah you are right. I mistyped:
* "Soṇa" returns 8 results
* "Soṇa.*" returns 16 results
I also looked at each result to verify that the search pattern showed up. It didn't previously.  Now it is searching for patterns in special places:

* en
* pli
* blurb
* title

Basically, if one can see it in Voice, one should be able to search for it.

**Comment by sabbamitta** [comment]
I can confirm that "sabbamitta" now returns only 2 results.

But I understood that the issue was actually that "sona" returns different results when spelled differently. And that is still the case.

**Comment by firepick1** [comment]
I think I changed my notion of what is correct. The way search currently works is this:

1. if any special Pali characters are detected, then an exact match for those characters is performed
1. for non-English search patterns,  all the "lookalike" letters are allowed in the search. E.g. a or ā

The interplay of these two rules causes "sona" to return 21 results for all the variations of "n" and "a".  Yet one can also use Voice to pinpoint "soṇā" vs. "soṇa". This is quite useful because sometimes names differ only in diacritics.

**Comment by sabbamitta** [comment]
Hmm... to my mind the majority of the users don't know much about diacritics. So they would miss what they search for if they don't have the correct spelling. This was a feature I appreciated very much about the Voice search, that it was not necessary to know the exact diacritics (I often don't), nor to have the capitals correct.

Those specialists who are searching for something more specific will still have that among their search results.

**Comment by firepick1** [comment]
Yes. Quite right. Most folks will just search for "sona". But every now and then I do need to search using diacritics and have it be accurate (e.g.,  "soṇā" vs. "soṇa").  Voice has always behaved this way, just not for "sona"

**Comment by sabbamitta** [comment]
That's new to me. I understood that in Voice search, neither diacritics nor capitals matter. ???

**Comment by firepick1** [comment]
I came up with this design many months ago and implemented it mostly correctly.  Now it works much as designed.  

I would be very grateful for your feedback ongoing as you watch yourself search both with and without diacritics.  The algorithm outlined above is generally useful, but I am quite sure there will be cases where we may want something else!

**Comment by sabbamitta** [comment]
​
I never search with diacritics actually! :-) (I find it too cumbersome to type them, unless I have to, and that's what I appreciated with Voice, that I don't have to - at least that's what I thought, but obviously I was wrong with his. :-))

I am not sure how much of a help I can be for testing this.

**Comment by firepick1** [comment]
That's actually perfect. It means you have not yet used diacritic search. The use case is this:

Suppose you read a sutta about Soṇā and you want to find other suttas about Soṇā. With the diacritic search feature, just copy Soṇā from the sutta and paste it into the search box. Voila! Problem solved.
No typing.

**Comment by sabbamitta** [comment]
:-)

**Comment by firepick1** [comment]
Ah. And for testing, all the suttas found by "sona" should contain either Soṇā or Soṇa in the search results (just open each result and look at the paragraph).  Then if you use diacritic search, observe that the other diacritic does NOT show up in the search results.

**Comment by sabbamitta** [comment]
My use case for Pali search is rather different: I want to search a Pali word and don't know exactly how it is spelled. I type it without diacritics - what do I get then?

**Comment by firepick1** [comment]
If you type a Pali word without diacritics, you get all possible diacritic variations (e.g., Soṇā + Soṇa)

**Comment by firepick1** [comment]
Oops sorry. I meant to update the comment, not close the issue.

**Comment by sabbamitta** [comment]
> NOBODY wants to type THAT. smile

Of course not! You made me quite smile a lot during our conversation about this issue. As I already said on D&D, your search feature is still much better than I suspected!

Maybe we can in fact close the issue; but I am too tired now, will just look again tomorrow.

:sleeping_bed:

**Comment by sabbamitta** [comment]
With a rested head, I think the search now does exactly what it is supposed to do; therefore closing. :heart:
