### ISSUE TITLE
an8.49:3.2; Aditi; Aditi completely ignores m-dashes, doesn't even make as much of a break as just between two words.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#129]
Yet we haven't built an AN-VSM... so there's still time to fix this. :-)

**Comment by firepick1** [comment]
This is fixed in v1.6.17.

Sadly, it invalidates all Aditi VSMs, given that emdashes are everywhere.

**Comment by sabbamitta** [comment]
Testing: It's now nicely read.

Is there a way of searching for m-dashes just in the Pali, respectively in Pali and a particular Nikaya? What we need to know is KN, DN, and MN.

If there are, this will postpone my VSM building plan. For billing reasons I will stick to make one VSM per month and not more, so everything will start anew. Or else, we leave them for the time being and then re-build them when everything else has been done. Who knows, there might come more Aditi bugs still.

Closing this issue now.

**Comment by firepick1** [comment]
The emdash occurs 5369 times in the Pali of Bhante's translations.

**Comment by sabbamitta** [comment]
> The emdash occurs 5369 times in the Pali of Bhante's translations.

Oh wow! :open_mouth: Is this really in the Pali, or are English translations included?

**Comment by firepick1** [comment]
Just pali. 😸
