### ISSUE TITLE
Update search Wiki page

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#13]

**Comment by sabbamitta** [comment]
Thanks for your cooperation in updating this page, @firepick1. I have still done a few edits and am now handing it over to you for revision. Please feel free to edit as you see fit, and please correct my English where necessary.

**Comment by firepick1** [comment]
Anagarika, please close after reviewing my recent change on search

**Comment by sabbamitta** [comment]
Approved with a slight new edit. :heavy_check_mark: Closing.
