### ISSUE TITLE
SN1.19 does not always show Bhante's Pali audio link

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#131]
Even though it works on localhost.

**Comment by firepick1** [comment]
This was rather peculiar:

1) Voice has an audio-url cache that kept things for a day
2) The website with Bhante's recordings also has a cache

What happened was the Voice cache remembered the first result from the recording website. That first result didn't exist for Pali and Voice simply cached that non-existence. Then a few seconds later, the recording website filled its own cache, but Voice was ignoring it since it was using its own cache.

To fix this, I reduced Voice's cache to only five minutes. This means that if this happens again, it will fix itself within five minutes.

v1.6.9

**Comment by sabbamitta** [comment]
Maybe you also meant to appoint me for testing? In this case I can confirm that after the fix all links are showing in SN 1.19. Closing.
