### ISSUE TITLE
UX to set expectations that Voice only hosts supported content, not all of the vastness of SC.

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#134]
Voice only searches supported suttas, so it can't find anything in non-Sujato translations.  This is by design and would be an issue for those using Voice improperly for academic research.

**Comment by Aminah-SC** [comment]
With the updated design for the "More" menu ([see here](https://discourse.suttacentral.net/t/sc-voice-development-cycle-v1-6/13163/228?u=aminah) are the two of you satisfied with the resolution of this issue?

**Comment by sabbamitta** [comment]
For my part: :heavy_check_mark:

**Comment by sabbamitta** [comment]
Karl: https://discourse.suttacentral.net/t/sc-voice-development-cycle-v1-6/13163/456?u=sabbamitta

Closing.
