### ISSUE TITLE
An8.49:1.3; Aditi; "Ekamantaṃ nisinnaṃ kho visākhaṃ migāramātaraṃ bhagavā etadavoca:"—Aditi says "colon" at the end.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#136]
There must be many colons in the suttas, but this is the first time I hear Aditi pronounce it.

**Comment by firepick1** [comment]
Fixed in v1.6.18.

There are now three pausing characters: colon, semicolon and emdash.

**Comment by sabbamitta** [comment]
Testing: :heavy_check_mark: 
Closing.
