### ISSUE TITLE
New settings UI

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#141]
#### User story

Voice's current settings have a number of accessibility issues documented in research videos (see [eg](https://drive.google.com/open?id=1aIV-Q2sLN2n10pzhU9fUvc6ygb42hnQG)) and in the description of [Sylvie's user experience](https://discourse.suttacentral.net/t/voice-development-cycle-v1-4/12497/165?u=aminah). :sob:

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

The settings should be redeveloped according to this re-design

![resources_settings_02 03](https://user-images.githubusercontent.com/36522678/61407396-ef726080-a8dd-11e9-8ffb-33a43516779f.jpg)

###### English Reader

[_As pictured above. Inclusion of the "Sujato (if available)" option well depend on development elsewhere_]

###### Pali Reader

[_Radio button_]

🤖 Aditi
🗣 Sujato (if available)

###### Languages

[_Radio button_]

English and Pali
English only
Pali only

###### Search Results

[_Radio button_]

5 results
10 results
25 results
50 results (slow)

###### "Inspire Me!" Button

(Results based on your chosen reader/s)

[_Radio button_]

Any length [_Default_]
less than 8mins
less than 30mins
longer than 45mins

###### Bell

[_Radio button_]

None
Indian bell
Tibetan singling bowl
Mid-range bell
Simple bell

###### General

[_Tick boxes_]

Show SuttaCentral text segment reference numbers
Store settings using web browser cookies

**Comment by sabbamitta** [comment]
Add check boxes instead of radio buttons for language selection, so that other combinations than just root language/translation language become possible. Settings should allow for combinations like English/German, or Pali/English/German; likewise with other languages as segmented translations become available.

**Comment by sabbamitta** [comment]
Play/download in two translation languages is made into a separate item and will be addressed in a later release.

One settings section closes automatically when another one is opened is made into a separate item and made an optional item for this release.
