### ISSUE TITLE
Time estimates are only shown for search lists with more than one sutta.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#147]
#### Bug Description
When my search list has only one sutta there is no time estimate. It is only shown for longer search lists.

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
Fixed in v1.6.31

**Comment by sabbamitta** [comment]
Fixed in v1.6. :heavy_check_mark:
Closing.
