### ISSUE TITLE
Add unexpanded version of MN 1.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#150]
#### User story

Since MN 1 has been fully expanded, though responding to the needs of some, there are probably more users for whom this is just too long to listen to.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Make an unexpanded version of MN 1 and make it the default.
- [ ] Add the expanded version to "More".

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
As it turns out, it was too much trouble to expand the bilara-data MN1, so....it is unexpanded.

**Comment by sabbamitta** [comment]
The time estimate says 20 min and something which sounds pretty reasonable. and I do see indeed ellipses … So yes, closing. :heavy_check_mark:
