### ISSUE TITLE
Upgrade to Vuetify 2.0

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#157]
Vuetify 2.0 has support for:

1. Internationalization (i18n)
2. Accessibility (a11y)

**Comment by firepick1** [comment]
Anagarika, Voice+Vuetify 2.0 is ready for testing as v1.7.3.  Please feel free to create new issues for any oddities you may find. I took care of a lot of odd stuff already (e.g., the links turned blue and had to be forced to our normal white again) but expect there to be a lot more issues lurking out there. No need to look for specific things, just be your normal mindful self as you use staging. Thank you!

**Comment by sabbamitta** [comment]
Huhu... I did in fact just notice the first bug, immediately after updating the staging server:

![Bildschirmfoto vom 2019-08-09 22-06-30](https://user-images.githubusercontent.com/43345786/62806071-18a79a80-baf2-11e9-8db5-8e1512c46b8a.png)

**Comment by sabbamitta** [comment]
Look into the settings: There are no boxes to click any more; only when scrolling with your mouse over an item there are dots showing up: grey (not selected) or purple (selected).

![Bildschirmfoto von 2019-08-10 21-42-44](https://user-images.githubusercontent.com/43345786/62826247-70a8d480-bbb8-11e9-8bd7-0ab137ef08b3.png)

![Bildschirmfoto von 2019-08-10 21-42-49](https://user-images.githubusercontent.com/43345786/62826253-8b7b4900-bbb8-11e9-97c0-cd103e6e0551.png)

**Comment by sabbamitta** [comment]
The sutta player too looks different:
![Bildschirmfoto von 2019-08-10 21-53-30](https://user-images.githubusercontent.com/43345786/62826434-c468ed00-bbbb-11e9-90f9-aa2b62cb1025.png)

compared to production:

![Bildschirmfoto vom 2019-08-10 22-07-53](https://user-images.githubusercontent.com/43345786/62826439-d3e83600-bbbb-11e9-9718-22776bdc0572.png)

**Comment by sabbamitta** [comment]
* When playing the sutta player the text is no longer highlighted in blue any more while playing.
* Staging server can't be updated… The boxes to check “step 1” and “step 2” have disappeared, and the “restart” and “update” buttons just do… nothing!
/home/sabbamitta/Schreibtisch/Bildschirmfoto vom 2019-08-11 19-00-39.png

**Comment by sabbamitta** [comment]
"Releases" has in fact the same check box issue as "settings"; the server could be updated by now. But v1.7.4 doesn't fix the check box issue.

---
Another issue on the "VSM" page for admins: The "true" and "false" comments in the "installed" column have disappeared.

**Comment by sabbamitta** [comment]
Check box issue both in "settings" and on the "Release" page fixed in v1.7.5. :heavy_check_mark:

**Comment by firepick1** [comment]
Thanks for testing, Anagarika!
I'll turn my attention now to i18n. Yay!

**Comment by sabbamitta** [comment]
Blue highlighting in the sutta player is back. :heavy_check_mark:

**Comment by sabbamitta** [comment]
v-data-tables in:
* VSM :heavy_check_mark: 
* Caches :heavy_check_mark: 
* Logs :heavy_check_mark: 

Thanks for all the :beach_umbrella:'s!! :wink:
