### ISSUE TITLE
Segmented audio downloads do not support human audio

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#159]
Download SN2.3 with Sujato for Pali and English. No audio.

**Comment by firepick1** [comment]
The root cause of this problem was that webm files need to be converted to mp3 files with a sampling rate of 22050 KHz so that they can be concatenated with AWS Polly audio segments. We do lose some fidelity in the conversion to MP3, but Voice does provide links to the original recordings by Bhante Sujato.  Fixed in v1.7.48.

**Comment by sabbamitta** [comment]
Tested with SN 1.19, sujato_pli + Matthew. :heavy_check_mark: 
Closing.
