### ISSUE TITLE
Add a faster English voice

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#163]
#### User story

When listening to long suttas it takes too long with the existing voices.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] 

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
I decided to go with Michael +0%. DN33 takes 79 minutes at this rate, which is fine.

**Comment by sabbamitta** [comment]
Good! Closing.
