### ISSUE TITLE
Matthew says "private" strangely in DN33

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#164]
Search for "public and in private" with Matthew.  Matthew speaks "private" like "priiiiiiivate" in a very unnatural way.

https://35.176.116.11/scv/audio/dn33/en/sujato/Matthew/bbac3bd7d7f204e1c113f0271a7ede58

**Comment by firepick1** [comment]
Fixed in v1.7.31

**Comment by sabbamitta** [comment]
Sounds good to me.

**Comment by sabbamitta** [comment]
Closing.
