### ISSUE TITLE
Matthew says "blue tint" strangely in DN33

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#165]
Sounds like "blue dent"

Search for "blue tint" and play quote using Matthew.

**Comment by firepick1** [comment]
Fixed in v1.7.31. Also reported bug to AWS Polly. Doubt they will fix, so we have our own workaround.

**Comment by sabbamitta** [comment]
Sounds good to me.

**Comment by sabbamitta** [comment]
Closing.
