### ISSUE TITLE
German voices

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#172]
#### User story

Implement three German voices:
1. Vicki rate -20%, pitch -10% (slow)
1. Hans rate -20% (medium)
1. Marlene rate +/-0% (fast)

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Add to settings

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
The voices are implemented but not testable since we have no content yet. This needs to be resolved after we have content.

**Comment by sabbamitta** [comment]
Working in v1.7.67 :heavy_check_mark: Closing.
