### ISSUE TITLE
Convert English sc-suttas to new folder format with language folder first

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#174]
For example, SN12.2 should go into:

* OLD WAY:   sn/en/sujato/sn12.2.json
* NEW WAY: en/sn/sujato/sn12.2.json

This rework is a prerequisite for i18n since it allows us to search for all suttas in a given language under one folder.

**Comment by sabbamitta** [comment]
Done in v1.8 :heavy_check_mark: 

Closing.
