### ISSUE TITLE
Update/create Bilara JSON files from Anagarika's german translations

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#176]
#### Description

Create a script that updates Bilara from Anagarika's Github [translation repository](https://github.com/sabbamitta/sutta-translation).

* Add segment numbers using Bhante Sujatos English translations as reference.
* Create suttaplex.json using `:tagged:` paragraphs
* Apply changes to sc-voice/bilara-data

#### Acceptance criteria 

- [ ] _What needs to be done for this issue to be completed_

**Comment by firepick1** [comment]
We should use Bilara JSON

**Comment by sabbamitta** [comment]
Merging with issue #162 .

**Comment by sabbamitta** [comment]
Done in v1.8 :heavy_check_mark: 

Closing.
