### ISSUE TITLE
For Deutsch, default translator should be Geiger/other German translators

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#180]
Default translator for English is "sujato".
Default translator for Deutsch should be "sabbamitta" followed by "geiger".

The following searches should be equivalent to `sn12.3/en/geiger` if Language is Deutsch:

* `sn12.3` 
* `sn12.3/de`

**Comment by sabbamitta** [comment]
Works in v1.7.67 :heavy_check_mark: Closing.
