### ISSUE TITLE
Acknowledgements UI

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#182]
Problem: We need an unobtrusive yet easily discovered place for acknowledgments: dedication, credits, references, etc.

Proposal: Put all these in a Voice wiki page whose contents are automatically rendered on the home page during extended periods of user inactivity.

**Comment by sabbamitta** [comment]
Separate Acknowledgements pages for [English](https://github.com/sc-voice/sc-voice/wiki/Acknowledgements) and [German](https://github.com/sc-voice/sc-voice/wiki/Dank) have been made, with a link from the respective Home page.
