### ISSUE TITLE
Make Português voice Ricardo speak legacy texts

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#187]
#### User story

When I use Voice it would be great if I were able to … because …

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] 

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
It seems this is already done, @firepick1 ?

**Comment by gnlaera** [comment]
Approved.
