### ISSUE TITLE
an10.2:1.0.6; Ricardo; êxtase: see below

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#191]
The only quirk was how it pronounces êxtase .

It is a legit Portuguese word but Ricardo got it wrong. The first syllable should be longer.

[See here.](https://discourse.suttacentral.net/t/wanted-translator-for-sc-voice-interface/13928/70?u=sabbamitta)

It should read aecstase or ɛkstɑz

https://michaelis.uol.com.br/palavra/MYPoE/extase/

**Comment by firepick1** [comment]
Fixed in v1.8.6
