### ISSUE TITLE
Highlighting bugs

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#207]
#### Bug Description
Instead of highlighting the search term, the code is shown in some cases. Example: "ein gerechter und rechtmäßiger Köning".

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
Fixed in v2.0.1

**Comment by sabbamitta** [comment]
:heavy_check_mark:
