### ISSUE TITLE
Loading bug for German legacy suttas

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#208]
#### Bug Description
When entering a sutta id for a sutta that has no segmented translation yet, the sutta player takes endless time loading and doesn't play the sutta.

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
fixed in v2.0.6

**Comment by sabbamitta** [comment]
Seems to work fine now! :heavy_check_mark:
