### ISSUE TITLE
Changes for English reading voices

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#226]
#### Description

According to [poll](https://discourse.suttacentral.net/t/poll-on-sc-voice-reading-voices/14533?u=sabbamitta)

Brian voice wins over Russell

#### Acceptance criteria 

- [ ] _What needs to be done for this issue to be completed_

**Comment by firepick1** [comment]
fixed in v2.2.11
Brian has replaced Russell. People with Russell will now hear Amy.

**Comment by sabbamitta** [comment]
With enough coffee Brian is doing an excellent job on staging! :heavy_check_mark:
