### ISSUE TITLE
For long suttas, download fails.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#245]
#### Bug Description
"Playlist is too long to be played", for DN33 pli/de, as well as monolingual de Vicki.

#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
Actually, monolingual works. So the bug is for bilingual. Given that the single language download is 2h13m, the value of the bilingual download is questionable.

**Comment by sabbamitta** [comment]
For me monolingual download for Marlene failed many times, and so does Vicki.

**Comment by sabbamitta** [comment]
For long suttas, download failes *sometimes*, depending on internet speed.
