### ISSUE TITLE
For DN33 blurb text is shown in English.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#247]
#### Discovered on:
 - OS: [e.g. Ubuntu 16.4]
 - Browser & Version: [e.g. chrome, safari]

**Comment by firepick1** [comment]
Interesting bug. The DE blurb only appeared in certain suttas. Now it should appear in all. sc-voice v2.1.20

**Comment by sabbamitta** [comment]
:heavy_check_mark: Closing.
