### ISSUE TITLE
One settings section closes automatically when another one is opened

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#265]
#### Description
if possible a previously opened setting subsection (Website language, translation etc.) should close, if another one is opened. If I open three at the same time the settings dialogue extends off screen (I have a 1920X1080 screen, so it’s not tiny). It’s not such a big deal, however, as the user can close what they’ve opened manually.
See https://discourse.suttacentral.net/t/sc-voice-development-cycle-2-2/15146/44?u=sabbamitta

#### Acceptance criteria

- [ ] a design agreed on by team members (if possible prototyped on a dedicated branch)
- [ ] if applicable, the creation of a ticket with a spec understood & agreed by team members

**Comment by firepick1** [comment]
fixed in v2.3.27

**Comment by sabbamitta** [comment]
> fixed in v2.3.27

:heavy_check_mark:
