### ISSUE TITLE
Edit Wiki after changes in UI

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#268]
#### Description
After making changes in the settings UI the Wiki has to be adapted accordingly.

#### Acceptance criteria 

- [ ] _What needs to be done for this issue to be completed_

**Comment by sabbamitta** [comment]
Please have a look at the [settings page](https://github.com/sc-voice/sc-voice/wiki/Settings). Actually, there wasn't much to update since there wasn't much written anyway. I just added a screen shot of the new settings for en and de.

**Comment by firepick1** [comment]
I edited the wiki. https://github.com/sc-voice/sc-voice/wiki/Settings 
Please close/review as you see fit.

**Comment by sabbamitta** [comment]
I edited the German version accordingly.
