### ISSUE TITLE
Rename Home@language wiki pages using ISO codes

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#270]
All wiki language pages for Home should end with ISO 2 letter codes:

* Home-DE.md
* Home-JA.md
* Home-PT.md
* Home-FR.md
* etc.

Existing wiki pages such as Home@Deutsch.md should be removed after the 2.2 release and all links should be updated to use new page names.

**Comment by sabbamitta** [comment]
Done for v2.2.
