### ISSUE TITLE
Adjust Voice code to accommodate Vinaya texts

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#298]
#### Description

The Vinaya texts have quite different and much more complex ID numbers than the suttas. In order to display the Vinaya in Voice, code has to be adjusted.

#### Acceptance criteria 

- [ ] _What needs to be done for this issue to be completed_

**Comment by firepick1** [comment]
Fixed in scv-bilara, which searches vinaya given <kbd>-up</kbd> flag. Voice does not search unpublished text

**Comment by sabbamitta** [comment]
Works in scv-bilara. Issue can be closed for now, another one is opened for allowing Vinaya search for Voice when Vinaya is published.
