### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#3]
A full review of each of Voice component/page as broken down in the sub-issues needs to be conducted

See [Sylvie's user experience](https://discourse.suttacentral.net/t/voice-development-cycle-v1-4/12497/165?u=aminah).

#### Outcome 

- [ ] Findings documented in each issue 
- [ ] The generation of new issues to address any problems highlighted

**Comment by firepick1** [comment]
The accessibility audit has revealed that the next logical step is voice recognition.
