### ISSUE TITLE
Use ripgrep instead of grep for scv-bilara

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#301]
ripgrep is faster and will become necessary as scv-bilara searches more and more

* ripgrep is faster
* ripgrep is Unicode aware
* ripgrep can search for "\bÜbung"
* ripgrep doesn't generate useless 0 count lines with -c option

**Comment by sabbamitta** [comment]
Confirming: Ripgrep is working and finds "Übung"; both in scv-bilara and Voice staging.
