### ISSUE TITLE
Make Voice show expandable text in both Pali and translation

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#317]
#### User story

There are users who like reading suttas, and would like to see the root text along with translation. Also, when searching a Pali term it is good to be able to see the text in Pali with the search string highlighted in the text.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] 

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
Pali now shows up now in suttas with Voice v.2.3.13
Voice is now bilingual

**Comment by sabbamitta** [comment]
Side by side view is too narrow on mobile.

**Comment by sabbamitta** [comment]
Is working fine both on desktop and mobile.
