### ISSUE TITLE
Long words don't display properly on Android phone (and probably other phones too).

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#33]
#### Long words go over the margin of the sutta player, i.e. AN10.17:8.1; SN51.13:1.9; SN51.13:2.7; SN51.13:3.7; SN51.13:4.7
Screenshot see: https://discourse.suttacentral.net/t/scv-development-v1-3/12312/442?u=sabbamitta

#### Acceptance criteria

- [ ] a design agreed on by team members (if possible prototyped on a dedicated branch)
- [ ] if applicable, the creation of a ticket with a spec understood & agreed by team members

**Comment by firepick1** [comment]
Possible fix with lang:la per Bhante

https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens

**Comment by sabbamitta** [comment]
Has been fixed with issue #373  in v2.3.
