### ISSUE TITLE
sn54.13:3.2; Aditi; Says "bosjhaṅge" and "bosjhaṅgā" instead of "bojjhaṅge" and "bojjhaṅgā"

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#354]
Related to issue #332 : Aditi; says "dhammavicayasambosjhaṅgaṃ" instead of "dhammavicayasambojjhaṅgaṃ"

**Comment by firepick1** [comment]
Voice v2.3.35

**Comment by sabbamitta** [comment]
Fix is good. :heavy_check_mark:
