### ISSUE TITLE
Voice speaks Pali words and phrases

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#357]
#### User story

See discussion: https://discourse.suttacentral.net/t/pali-voice-recordings-for-anki/16333

Example: abhisambuddha

Should speak "abhisambuddhā" found in DN33

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] 

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
Speak each of the search results found.

**Comment by firepick1** [comment]
v2.3.36

**Comment by sabbamitta** [comment]
Download depends on browser; works with Chrome, not with Firefox.

**Comment by sabbamitta** [comment]
Speech bubble added to single result terms in v2.3.36.

**Comment by sabbamitta** [comment]
For the moment this seems to work reasonably well. If needed, further adaptation later.

**Comment by sabbamitta** [comment]
Change to relevance score: the scored phrases are required to start at the beginning of a word. v2.3.40.
