### ISSUE TITLE
On mobile: Voice shows code along with Sutta ID

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#358]
#### Bug Description
When going to a Sutta, Voice shows tome code along with the Sutta ID so that there is hardly space left for the actual text.

#### Steps To Reproduce:

1. Go to 'an3.99'
2. See error
 
#### Expected behaviour
It should just show the Sutta ID without code and leave more space for the actual text.

#### Screenshots
See https://discourse.suttacentral.net/t/sc-voice-development-cycle-2-3-part-2/15911/310

#### Discovered on:
 - Device: Android

**Comment by firepick1** [comment]
Not reproducible. Fix unknown.

**Comment by sabbamitta** [comment]
Looks like autofix! :-)
