### ISSUE TITLE
Overly long pali words cause problems in app

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#373]
#### Bug Description
See description and screenshots here: https://github.com/w3c/csswg-drafts/issues/5270
 
#### Expected behaviour
Long words are hyphenated and fit into columns.

#### Fix:
Use Latin as alias language for Pali.

**Comment by firepick1** [comment]
This bug is unexpectedly nasty. Chrome only fixed hyphens on Mac and Android. It did not fix it for my Chromebook or Windows. They have known about this issue since 2016, and are ignoring it.

**Comment by sabbamitta** [comment]
As I understood Bhante, the trick with Latin would work for Firefox, not Chrome. For some users Firefox would be helpful, but unfortunately not for all.

**Comment by firepick1** [comment]
Yes. Quite right. Voice supports Chrome, so I'll need to write special code to deal with long Pali words. I doubt Google will fix Chrome in my lifetime.

**Comment by sabbamitta** [comment]
Too sad! Thanks for taking the trouble.

**Comment by firepick1** [comment]
fixed in v2.3.56 for both sutta player and regular sutta view

**Comment by sabbamitta** [comment]
Seems to work both with Chrome and Firefox.
