### ISSUE TITLE
Isolate translatable user interface text into language modules.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#38]
#### User story

When Voice will have languages other than English user interface text will have to be translated.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] A file is created that translators can use.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
Priority will change as soon as Bilara is ready.

**Comment by firepick1** [comment]
This is complete with v1.7.28, which also was the Setting to switch between English and Deutsch for the Website Language.

**Comment by sabbamitta** [comment]
Thank you so much! Serving as a template for translation should be enough of a test for this!
Closing.

**Comment by sabbamitta** [comment]
> which also was the Setting to switch between English and Deutsch for the Website Language

Testing this: I can switch from German to English but not back again.

**Comment by firepick1** [comment]
The locale setting is now set when using cookies. v1.7.30

**Comment by sabbamitta** [comment]
... and it works fine! :smiley: 
Closing.
