### ISSUE TITLE
Trilingual search for DE returns results that have no DE translation

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#381]
#### Bug Description
Searching for `./scripts/de-search -ml 3 hindrance` in scv-bilara returns among others `sn46.36:0.2`, a segment from a Sutta that has  no German translation yet.

Looking around, I see that for Portuguese AN and SN translation stubs have been added to bilara-data.
#### Steps To Reproduce:

1. Search for `./scripts/de-search -ml 3 hindrance` in scv-bilara.
2. See error
 
#### Expected behaviour
`./scripts/de-search -ml 3` should only return result with third language = de; i.e. pli + en + de.

#### Additional context
With more translators working in Bilara more texts in different languages are added.

**Comment by firepick1** [comment]
Diagnosis is that the silly blank stub files are confusing scv-bilara. Scv-bilara needs to check that they are empty now. I'll tackle that tomorrow...

**Comment by sabbamitta** [comment]
I am not sure if checking if the files are empty is enough here. I think that all results that are *not* DE should be excluded from trilingual DE search, such as Portuguese or others. Trilingual DE search should only return results that have PLI + EN + DE.

**Comment by firepick1** [comment]
Stub file was too big. Stub files used to be "{}". This stub file was different. Someone put a newline in it.  I really don't like stub files. They are as useless as "this page left intentionally blank"

Fixed in scv-bilara v1.3.51

**Comment by sabbamitta** [comment]
Okay, good. Wrong search result isn't shown any more.
