### ISSUE TITLE
Pali Hyphenation for Ayya Vimala (following bug fix #373 )

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#385]
https://discourse.suttacentral.net/t/average-word-length-as-indicator-of-pali-text-age/15204/37

**Comment by firepick1** [comment]
Moved into v2.3 per Anagarika Sabbamitta's suggestion. Incorporating Ayya Vimala's Python code will improve Voice hyphenation for Pali.

**Comment by sabbamitta** [comment]
Following bug fix #373

**Comment by firepick1** [comment]
Created js-ebt for Ayya VImala and Voice. Voice now uses pali-hyphenator in client v2.3.68.  Ayya Vimala is happy for now so I think we can close unless you find another issue

**Comment by sabbamitta** [comment]
Hyphenation of Pali words is working properly in Chrome and Firefox.
