### ISSUE TITLE
Investigate Pali aeneas synchronisation map for sutta recordings 

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#4]

**Comment by firepick1** [comment]
[Segmented audio files](https://discourse.suttacentral.net/t/my-new-project-recording-the-suttas/12369/48?u=karl_lew) split according to the aeneas JSON map do not quite line up with the text. Progress is blocked. Seeking assistance from MichaelH

**Comment by firepick1** [comment]
Still blocked but exchanging ideas with Bhante. Apparently this affects Pali more so than English.

**Comment by firepick1** [comment]
Current Pali automatic segmentation by Aeneas is not usable. There is little correspondence between text and audio other than at the start and the end. We have tried various solutions (e.g., non-Unicode) to no avail.

**Comment by firepick1** [comment]
Bhante is OK with Aeneas segment alignment. We will use as is. Closing.

**Comment by firepick1** [comment]
Reopened and assigned to Anagarika to confirm that segmentation splits are acceptable. Sometimes they are off by several words.  Even with such bad errors, Bhante was not bothered.

**Comment by sabbamitta** [comment]
Tested for availability on Voice: SN1.1-59 are available right now. Further progress depends on Bhante Sujato for recording and Michael H for uploading.

Acceptability of segment splits: I can confirm that sometimes they are off by several words. If Bhante shrugs his shoulders at this, I too shrug. :woman_shrugging: Shrugging in concert! :man_shrugging: :woman_shrugging: :man_shrugging: :grinning: 

Issue closed.
