### ISSUE TITLE
Aditi: anther swallowed "a" in a 5 letter word—so we might lower the limit for spacing again.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#40]

**Comment by sabbamitta** [comment]
AN4.57:1.2 "āsane"

**Comment by firepick1** [comment]
Fixed in v1.3.17. Changed syllabifyLength=5.  Affects all Aditi content and therefore requires regression testing.

https://discourse.suttacentral.net/t/scv-development-v1-3/12312/510?u=karl_lew
