### ISSUE TITLE
Admins can start/stop AWS SCV servers

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#41]
#### User story

SC-Voice should become independent of its originator

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] It should be possible to start / stop AWS Voice servers via Admin login.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
Duplication: Merge with issue #279 .

**Comment by firepick1** [comment]
The Voice AWS production login link for *sabbamitta* is
https://870712634613.signin.aws.amazon.com/console?region=us-west-1

This use can start/stop production Voice servers

**Comment by sabbamitta** [comment]
Test successful.
