### ISSUE TITLE
Scv-bilara search and Voice search don't find "alles leiden, das zustande kommt"

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#434]
#### Bug Description
As per title. When I search for "alles leiden" only I get other results, but not this one.

#### Steps To Reproduce:

1. Go to scv-bilara terminl
2. Search with `./scripts/de-search -ml 3`, search string "alles leiden, das zustande kommt"
3. See error: no result

Try the same in Voice ==> no result either.

#### Expected behavior:

Result: sn42.11:2.16.

#### Context:

Maybe we should make search disregard quote marks entirely. For: When searching for "alles leiden" it's the instances that start with a quote (single quote in that case) that are not found, namely sn42.11:2.10 and sn42.11:2.16. Even if I type the quote with the search string it is not found. sn42.11:2.12 however is found.

**Comment by firepick1** [comment]
fixed in Voice v2.4.52 and scv-bilara v1.3.69

**Comment by sabbamitta** [comment]
Works in both contexts. :heavy_check_mark:
