### ISSUE TITLE
scv-bilara mistakes Fingerschnippen to be an English word 

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#448]
The words-en.txt file contains "fingers", which is English. Perhaps that may be involved. But also see "blind" which is both a German and an English word.

**Comment by sabbamitta** [comment]
It also mistakes "auge" to be an English word.

**Comment by firepick1** [comment]
fixed in scv-bilara v1.4.6 for auge, fingerschnippen and makel

**Comment by sabbamitta** [comment]
Works; and with Voice v2.5.3 it works on staging, too.
