### ISSUE TITLE
Show notification in case SC is down

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#454]
#### Description
When SC is down, Voice also shuts down. Voice depends on SC for legacy texts, titles, legacy author information, etc.

Rather than shutting down in case it cannot access this information, Voice should instead notify the user that certain texts are currently not available. Voice can still remain functional with the content of bilara-data.

This case would currently apply to German legacy translations for those suttas that don't have segmented translations yet. If a user types `MN1` into the search box they should see
- MN1 legacy translation in case it is available.
- A notification text in case it is not available.

Suggestion for text:
`Der gewünschte Text ist momentan nicht verfügbar. Bitte versuchen Sie es später noch einmal.`

**Comment by sabbamitta** [comment]
A cache has been built for SC-API. Since there is no way to have a notification for changes that happen to SC this cache should be rebuild as a part of every Voice release process.

**Comment by firepick1** [comment]
Created suttacentral-api cache which stores all the suttaplex card information normally requested from suttacentral. By using the new cache, Voice is much more independent of Suttacentral and will keep working if SC crashes.

**Comment by sabbamitta** [comment]
A release instruction has been added to *About Voice*: https://sc-voice.github.io/sc-voice/en/490-release

**Comment by sabbamitta** [comment]
The error message will be the equivalent of `an3.12 Error: loadMLDocLegacy() not found:an3.12/cs`. All languages will have the same error message.

As long as Voice and SC are not down, there is no way of testing this.
