### ISSUE TITLE
Developers can effectively edit all sc-voice repositories

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#46]
#### User story

SC-Voice should become independent of its originator.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Developers other than the originator can effectively edit all sc-voice repositories.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
Anagarika Sabbamitta is editing scv-bilara and sc-voice, so we're done.
