### ISSUE TITLE
Prevent downloader from downloading non-existing texts

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#474]
#### Description

See discussion [here](https://discourse.suttacentral.net/t/sc-voice-development-cycle-2-5/17351/450?u=sabbamitta) and following.

If a wrong translation language is selected, Voice tries to download a non-existing text. This blocks the app, and probably not only for that one user. Once started, the download process cannot be stopped, except for by rebooting the server.

The process of building and downloading a sutta or a playlist should only be started if:
- the selected sutta(s) have a translation in the selected language, and
- there is a reading voice available for that language.

**Comment by firepick1** [comment]
Removed play and download icons for languages without voices (e.g., Czech)

**Comment by sabbamitta** [comment]
After fixing a few bugs it is now working.
