### ISSUE TITLE
Search is too slow

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#477]
#### Description
Searching for the same thing twice takes just as long. Users get frustrated waiting for the web page to respond.

#### Acceptance criteria 
Subsequent searches of the same thing should be faster.

- [ ] _What needs to be done for this issue to be completed_

**Comment by firepick1** [comment]
Created search memoizer that caches search results for both sc-voice and scv-bilara

**Comment by sabbamitta** [comment]
Tested and working.
