### ISSUE TITLE
Training the Pali/English word recognizers should not require NPM

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#479]
Pali/English word recognizers change frequently. Managing frequent releases via NPM is cumbersome. Ideally a simply update of Github would suffice.

**Comment by sabbamitta** [comment]
Test:
- Add new exception "stamm" on GitHub https://github.com/sc-voice/scv-bilara/blob/master/src/assets/words-en-exceptions.txt
- Pull changes to your computer
- Run `scripts/train` in scv-bilara
- Commit back to GitHub
- Reboot Voice server
- Both scv-bilara and Voice recognize "stamm" as a German word now. :heavy_check_mark:
