### ISSUE TITLE
Translators and Editors have content privileges: edit language dictionaries, voice definitions and examples.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#48]
#### User story

SC-Voice should become independent of its originator.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Add login for translators and editors to access and edit language dictionaries, voice definitions and examples.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
With Bilara and Github access for Anagarika @Sabbamita, this is done
