### ISSUE TITLE
Update Japanese web interface

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#482]

**Comment by kaz-kaz** [comment]
Changes (lines 158, 185 and 202) were made and done. Thank you.

**Comment by kaz-kaz** [comment]
Review the Japanese web interface file, https://github.com/sc-voice/sc-voice/blob/master/src/i18n/vuetify/ja.ts.

**Comment by sabbamitta** [comment]
New downloader interface works on local install.
