### ISSUE TITLE
Voice speaks "unburdensome" as Pali.

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#490]
Voice is using words-en.json, which is an English dicitionary that duplicates the work of scv-bilara. The "isForeignWord" method of Words.js should use the scv-bilara English dictionary.

See https://discourse.suttacentral.net/t/is-fixing-english-voice-part-of-your-work/16693/6?u=karl_lew

**Comment by kaz-kaz** [comment]
I listened. Thank you very much for fixing it. All good.
