### ISSUE TITLE
Investigate English aeneas synchronization map storage

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#5]

**Comment by firepick1** [comment]
This issue is rather vague. I am understanding it to mean "Put Bhante's English segmented audio on Voice"

**Comment by sabbamitta** [comment]
:joy: I guess it was you who created it. Whatever you now understand by it, that be it!

**Comment by firepick1** [comment]
Voice v1.6.19 is available for testing.

**Comment by sabbamitta** [comment]
Working! :laughing:
Issue closed.
