### ISSUE TITLE
Transition Voice operations to a different AWS account

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#50]
#### User story

SC-Voice should become independent of its originator.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Planning: draft a brief plan for the transition process (who is responsible for what, when etc)
- [ ] Phase 2: switch voice.suttacentral.net to new Elastic IP.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
We have had two other AWS accounts created and used for Voice. This is good enough proof that it can be done.
