### ISSUE TITLE
Voice ignores Japanese punctuation pauses in audio

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#503]
Kaz says: "Also I thought Takumi could pause a bit longer for Japanese quotation marks (dominantly、and 。）. I was not sure this is what you categorise as lesser issue or not."

**Comment by kaz-kaz** [comment]
Very sorry, not quotation marks, but punctuation marks.

**Comment by sabbamitta** [comment]
>Very sorry, not quotation marks, but punctuation marks.

Title has been changed accordingly.

**Comment by sabbamitta** [comment]
Has been solved by using slower rate.
