### ISSUE TITLE
Incorporate S3 Cloud Storage API into cache software to simplify cloud integration.

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#52]
#### User story

Sound cache requires a lot of storage space, and capacities on AWS servers are limited and expensive.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] S3 Cloud Storage API will allow to use not only Amazon but also other vendors who support this API. It is a prerequisite to moving caches to a cloud.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
Please edit the wording in the feature description. I'm not sure if I describe the issue well.

**Comment by firepick1** [comment]
The increase of EC2 storage to 16GB and the introduction of VSM modules means we no longer need this.
