### ISSUE TITLE
Redirect selected caches to a cloud storage service that supports AWS S3 Storage API

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#53]
#### User story

Sound cache requires a lot of storage space, and capacities on AWS servers are limited and expensive.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] According to storage space caches are moved to a cloud storage service as necessary.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
Increased EC2  storage to 16GB means we no longer need to do this.
