### ISSUE TITLE
Investigate Opus for Voice

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#54]
#### Description

CAF is the Apple Audio format. It may have advantages for offline listening. Perhaps an investigation would help.

Create Wiki page with investigation results for:

- [ ] Performance cost for on-the-fly conversion to CAF from Opus
- [ ] ffmpeg libopus vs. opus
- [ ] CAF support for offline listening
- [ ] CAF HTML5 support
- [ ] Performance cost for on-thefly conversion to MP3 from Opus

#### Acceptance criteria

- [ ] a plan agreed on by team members
- [ ] if applicable, the creation of a ticket with a spec understood & agreed by team members

**Comment by firepick1** [comment]
v2.5.18 supports opus, ogg, mp3

**Comment by sabbamitta** [comment]
After all bugs have been fixed it works fine now!
