### ISSUE TITLE
some typos

### ISSUE THREAD

**Issue by Manfredsuttacentral** [sc-voice/sc-voice#547]
#### Description
In https://suttacentral.net/thag4.12/de/sass?lang=de&reference=none&highlight=false
"und fand zurMönchsgemeinschaft hin" should be "und fand zur Mönchsgemeinschaft hin"

and 
"So harrte ichgeduldig aus" should be "So harrte ich geduldig aus"

Cheers,

Manfred

#### Acceptance criteria 

- [ ] _What needs to be done for this issue to be completed_

**Comment by sabbamitta** [comment]
Thank you Manfred! I've created a pull request https://github.com/suttacentral/sc-data/pull/290 for @ihongda to merge (and still found a few more typos). Please HongDa, take care when you have the time. :pray:

**Comment by sabbamitta** [comment]
Closing as completed.
