### ISSUE TITLE
Admin can update cache from VSM

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#56]
#### User story

As a Voice Admin, I can replace a Voice Nikaya cache with the latest sounds.

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Each cache in the Admin web page has a button that will open up a dialog to update the cache from a VSM

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by sabbamitta** [comment]
Tested successfully!
