### ISSUE TITLE
"Take a break" / "Long read" sutta filter

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#66]
#### User story

When using Voice sometimes I don't have a lot of time, or just want to take a quick break and recharge with some wholesome mind substances. I'd like an easy way to be able to filter for suttas that are less than 8 or 10 minutes. Likewise with longer suttas. 

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ] Integrate a filter to show the approximate length of a sutta / playlist before pressing "play".
- [ ] UI design.

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by Aminah-SC** [comment]
Here's a sketch of how this could be implemented from a UI perspective:

![filter-feature-sketch3 1](https://user-images.githubusercontent.com/36522678/58385366-8d892f00-7fef-11e9-8ac9-f58920c14ac1.jpg)

In the above there are two different buttons. “Inspire me!” works as it does currently, but down arrow brings:

![filter-feature-sketch3 2](https://user-images.githubusercontent.com/36522678/58385365-8d892f00-7fef-11e9-9bcc-ce19439ed576.jpg)

**Comment by sabbamitta** [comment]
This issue is merged with #7.
