### ISSUE TITLE
VSM: Voice Sound Modules

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#67]
#### User story

Each Voice server can be provisioned with a set of Voice Sound Modules (e.g. mn_eng_sujato_amy or mn_eng_sujato_sujato) that collectively define what users can hear and search for. Each VSM:

* has the sounds for a specific version of a single voice (AI or human)
* has the sounds for one language (e.g., en, pli, etc.)
* is associated with a specific revision of text from a single source/author
* shall be archivable to and restorable from a single file in S3-style cloud storage
* shall ideally be between 1MB-1GB
* shall be associated with a conventional collection (e.g., Majjhima NIkaya)

The above constraints arise out of user as well as storage requirements and align well with Voice settings that permit choice of voice, language and translator. They also support the anticipated Offline Voice application.

---
As at the moment no Voice admin has the option of using AWS free tier for Polly voices there will have to be a few preliminary steps before actually building VSMs. Also, it seems that AWS voices for German are not as good as for English and Pali (the latter being very much hand customized and not easily available from other vendors).

As more languages may be added to Voice in the future there arises the need to explore other TTS vendors to find the best possible voices. Another aspect is also that it may be more favorable to use localized servers to the countries of the various languages.

The issues in this Epic are supposed to address these various steps and aspects.

**Comment by firepick1** [comment]
I think we are creating VSMs and they work. So we are done?

**Comment by sabbamitta** [comment]
Ah, well, you think we could close this Epic? There is still this one issue that will still be in production for quite a while, #119. Apart from that we are done.

**Comment by firepick1** [comment]
Ahhhhhhhh. Of course. Thank you.

Then this epic should be In Progress assigned to you to do the honors.

**Comment by sabbamitta** [comment]
With the implementation of SayAgain, VSMs have lost their importance. Maybe they will be resumed at a later date under new circumstances.
