### ISSUE TITLE
UX design for new and existing resources

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#7]
#### Description

Subsequent to research around how segmented human voice recordings will be added to Voice, a new design will need to be drafted to accommodate this addition. 

In addition, other resources (eg. audio of legacy translations) are currently deeply buried on Voice and many users will likely be unaware that they exist. We need to improve their visibility.

The redesign should be done with reference to any a11y issues testing has highlighted 

#### Considerations 

- An AI  fallback option is needed for texts that aren't covered by human voice recording.
- The UX should be designed to accommodate multiple human voices.
- The UX should be accessible (and Vuetify components generally aren’t)
- Users should be able to set different preferences (AI/human) for readings of root text and translation.

#### Acceptance criteria

- [ ] a11y tested
- [ ] a design agreed on by team members
- [ ] the creation of a ticket with a spec understood & agreed by team members

**Comment by Aminah-SC** [comment]
Draft UI for integrating human readings into voice pushed to https://github.com/sc-voice/sc-voice/tree/humanUI (also see #110)

**Comment by Aminah-SC** [comment]
@firepick1 Following on from this first rough impression:

![resources_01 01-more](https://user-images.githubusercontent.com/36522678/58374679-7fc9a000-7f42-11e9-92e9-9a9dab2a60db.jpg)

I've created a new [`resources` branch](https://github.com/sc-voice/sc-voice/tree/resources). Whenever you're ready, perhaps you could do the necessary piping to add the functionality, after which I can do any remaining css work if needed, as well some accessibility tweaks. 

As you'll see I thought it best just to use the icon alone (rather than with the word "More"), but other than that the image gives a fairly good idea of the direction of travel and I've left a bunch of comments in sutta.vue (search for "@KARL"). 

Some [Material icons](https://material.io/tools/icons/?icon=create&style=baseline) that might be handy:

`remove` (for collapsed button)
`call_made` (to indicate a link will take you to an external site)
`mic_none` (if it will work, it would perhaps be good to use this icon rather than the text "(Reader)" and shift the text to a tooltip; see comment in sutta.vue)
`create` ([As above] … "(Trans.)" …)

**Comment by Aminah-SC** [comment]
Following on from D&D discussion, here is the updated design for the human voice settings integration (and settings overhaul). As noted, some details are yet to be determined.

![resources_02 02-settings](https://user-images.githubusercontent.com/36522678/58385218-31bda680-7fed-11e9-9f49-e51967a08ae2.jpg)

**Comment by sabbamitta** [comment]
Thank you very much, @Aminah-SC!

**Comment by sabbamitta** [comment]
I also referenced [another one](https://github.com/sc-voice/sc-voice/issues/109), but for some reason it doesn't show up here.

**Comment by firepick1** [comment]
I'm not sure how to make the pop-ups accessible. We need to chat more when Aminah has time. Let's bump this to v1.6

**Comment by Aminah-SC** [comment]
> I'm not sure how to make the pop-ups accessible.

Karl, can you maybe briefly outline what concerns/technical difficulties you envisage here? 

To begin with, I understand that there's no likelihood of finding any solution in Vue/Vuetify. Also, when we've discussed this, you've consistently used the term 'pop up' and I've consistently used the term 'dropdown menu' in my mind there is a significant difference between these two things, so it might be good if we begin by making sure we're on the same page. What is it that you understand/mean by 'popup', is that definitely the option to go for, and what implications does this have for delivering a new, accessible settings options?

In case it is helpful, here are a couple of articles on building accessible dropdown menus: 

https://dev.to/lkopacz/create-an-accessible-dropdown-navigation-114n
https://www.smashingmagazine.com/2017/11/building-accessible-menu-systems/

I know that the design in above (#issuecomment-496017883) has a bit more complexity with the radio buttons, but to get us rolling, maybe it's best if we start simple and address the basic concerns/issues you have.

**Comment by firepick1** [comment]
By pop-up I mean anything that appears visually as "on top of". This can include dropdown menus. I do not know how to make accessible drop-down menus. Vuetify dropdown menus are not accessible. Because of this, I have taken pains to avoid dropdown menus.

**Comment by Aminah-SC** [comment]
Okay much thanks, I really understand the difficulty. In terms of arriving at a solution then, I think this pretty much means that the start point of design has to be narrowed down to what actually is achievable. Would you be able to run through what you consider workable options? Or, taking it from a slightly different angle, when putting this ticket forward as one that would be good to address, what kind of outcome were you hoping for?

**Comment by sabbamitta** [comment]
Addressed in v1.6: New design with good accessibility for "More" (or "Other Resources").

Remaining issues that have been merged will be addressed in another ticket (to be set up by Aminah).

**Comment by sabbamitta** [comment]
Done in v1.6. Closing.
