### ISSUE TITLE
Add segmented human voice recording

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#8]
Bhante Sujato has begun [a project to record his reading of the 4 Nikayas in English and in Pali](https://discourse.suttacentral.net/t/my-new-project-recording-the-suttas/12369/45). These will be included in Voice, and a researched plan for doing so needs to be developed and carried out.

**Comment by firepick1** [comment]
We have added Bhante Sujato's current Voice recordings.
