### ISSUE TITLE
Search: sutta ID’s that include a space are not found

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#84]
#### Describe the bug
If a space is included between nikaya abbr and sutta id number (eg. SN[SPACE]45.161) voice does not return the searched for sutta, but instead a list of other suttas. 

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to 'search'
2. Enter 'SN 45.161'
3. See error
 
#### Expected behaviour
A user should be able to enter either "SN45.161" or "SN 45.161" in to search and have SN45.161 returned. 

#### Discovered on:
 - OS: Linux Mint 18
 - Browser: FF 66.0.1 (64-bit)

**Comment by firepick1** [comment]
Fixed in v1.3.22. Please update staging server and test.
