### ISSUE TITLE
Create 16GB staging server on AWS Aminah

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#85]
Create 16GB staging server on Aminah's AWS account. This server will be needed for VSM testing because of the large disk requirements. It will also be a test of the AWS Installtion wiki instructions which have been changed since last review.

- [x] Create 16GB staging server
- [x] Terminate existing 8GB staging server

**Comment by firepick1** [comment]
Aminah, I've arbitrarily given this 3 story points and assigned it to v1.5. We won't need this for v1.4.
Update as you see fit.

**Comment by Aminah-SC** [comment]
Okay, but I don't use the story points; they're pretty meaningless to me.
