### ISSUE TITLE
Preliminary research for adding segmented human voice recording

### ISSUE THREAD

**Issue by Aminah-SC** [sc-voice/sc-voice#9]
Some of the initial questions that need to be addressed to get started with the Epic are:

- can we split up Bhante’s recordings into segments?
- how will segments sound when glued back together?
- what happens when we interleave Bhante Pali with Bhante English segment by segment?
- what needs to be done to support the desire for Opus/OGG files vs. MP3?

#### Outcome:

- [ ] findings documented in comments below
- [ ] generation of new issues as appropriate.

**Comment by firepick1** [comment]
DUPLICATE
