### ISSUE TITLE
Provide full link to Bhante's Opus audio file

### ISSUE THREAD

**Issue by firepick1** [sc-voice/sc-voice#91]
#### User story

It should be easy for users to get to Bhante Sujato's audio Opus recording of a given sutta. 

#### Feature description (the list of things that need to be done for the ticket to be considered finished):

- [ ]  Link to Opus file in Other Resources details 

#### Pre release planning check:
- [ ] Small enough to completed in a release.
- [ ] Dependencies marked
- [ ] No external dependencies block this from being completed.
- [ ] Details are understood by dev team so they know what needs to be done and can determine if it can be completed.

**Comment by firepick1** [comment]
Fixed in v1.4.20.  Now the Audio links show only if there is audio.

![image](https://discourse.suttacentral.net/uploads/default/original/3X/5/d/5d92d29c8d4278cc2e6088dfe85ad580fd23b4a0.png)

**Comment by sabbamitta** [comment]
Excellent! It's a great achievement! Issue can be closed.
