### ISSUE TITLE
MN39:3.5 and MN39:4.7; Aditi; "paṭivedayāmi" is pronounced as "paṭidayāmi".

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#94]
This too happens repeatedly in other segments of this sutta.

**Comment by sabbamitta** [comment]
Added: MN36:16.1 "aggivessana" is pronounced as "aggissana".

**Comment by firepick1** [comment]
I think this is also fixed in v1.4.5. These are all related to "ve".
