### ISSUE TITLE
MN38:4.12 (and elsewhere); Aditi; In "sādhu" the "h" is overly emphasized, like "sāde-hu".

### ISSUE THREAD

**Issue by sabbamitta** [sc-voice/sc-voice#96]

**Comment by sabbamitta** [comment]
(Not sure if it occurred only after working on the "v" words, but didn't notice it before)

**Comment by firepick1** [comment]
Fixed in v1.4.15.
The syllabification was breaking up dh into "d h".

**Comment by firepick1** [comment]
Fixed "gh" in v1.4.17. Syllabification was too enthusiastic.
